apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django-container
        image: {{ACR-NAME}}.azurecr.io/{{IMAGE-NAME}}:{{IMAGE-TAG}}
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: database-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: secret-key
        - name: ALLOWED_HOSTS
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: allowed-hosts
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django
spec:
  selector:
    app: django
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: LoadBalancer
